#!/usr/bin/env bash
# Remplacer localhost
sudo sed -i 's/^127.0.0.1.*/127.0.0.2 localhost/' /etc/hosts

# Ajouter ou remplacer facebook.com
if grep -q "facebook.com" /etc/hosts; then
    sudo sed -i 's/.*facebook.com.*/8.8.8.8 facebook.com/' /etc/hosts
else
    echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
fi
